### ISSUE TITLE
SpaceAfter=\n vs SpacesAfter=\n

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Italian-TWITTIRO#10]
A few repos, particularly this one, use `SpaceAfter=\n` instead of `SpacesAfter=\n`.  Is that a bug?  I would think all such instances should be converted to `SpacesAfter=\n`

**Comment by dan-zeman** [comment]
The validator should now report this as an error.

**Comment by alessandrateresacignarella** [comment]
corrected this issue!
