### ISSUE TITLE
Segmentation sent_id=train_923

### ISSUE THREAD

**Issue by robvanderg** [UniversalDependencies/UD_Italian-TWITTIRO#4]
There is a SpaceAfter=No after a URL, this makes the txt file concatenate the word to the following sentence:

http://t.co/mmToHn5Mzola buona scuola di renzi ha avuto la sua apoteosi in

Should/could this SpaceAfter be removed?

**Comment by alessandrateresacignarella** [comment]
Thank you for your feedback, I corrected it :-)
